Feature/add gist option
yotamolenik/mobileconfig pull request #4
Opened 2022-10-20 09:57 UTC by yotamolenik

Payload_types:
  - Refactor the parsing to use OOP
  - Add an option for md file output

2022-10-20 14:17 UTC, doronz88 commented on mobileconfig/mobileconfig.py
> +
Remove these lines

2022-10-20 14:18 UTC, doronz88 commented on mobileconfig/__main__.py
> +# im not yet sure why, but pycharm thinks this import is wrong. in fact it works perfectly fine on my terminal
Are you?

2022-10-20 14:19 UTC, doronz88 commented on mobileconfig/__main__.py
> +import mdutils
Reorder your imports using pycharm. Third party ones should be grouped together

2022-10-20 14:21 UTC, doronz88 commented on mobileconfig/__main__.py
> -# im not yet sure why, but pycharm thinks this import is wrong. in fact it works perfectly fine on my terminal
Dont include this in the first commit in the first place if this is removed

2022-10-20 14:22 UTC, doronz88 requested changes
Fix comments and add a link into the gist page from the main readme

2022-10-23 07:07 UTC, yotamolenik commented on mobileconfig/__main__.py
> +# im not yet sure why, but pycharm thinks this import is wrong. in fact it works perfectly fine on my terminal
during the time of the 1st commit, yes. but i can remove it too now

2022-10-23 07:21 UTC, yotamolenik commented on requirements.txt
>  humanfriendly
nope, now removed

2022-10-23 07:21 UTC, yotamolenik commented on mobileconfig/mobileconfig.py
> +
done

2022-10-23 07:21 UTC, yotamolenik commented on mobileconfig/__main__.py
> +import mdutils
done

2022-10-23 07:52 UTC, doronz88 requested changes
It's almost there

2022-10-23 07:52 UTC, doronz88 commented on mobileconfig/mobileconfig.py
> +    def payload_content(self) -> 'PayloadContent':
this doesn't return the `PayloadContent`, just the RAW plist. return the correct object and refactor accordingly

2022-10-23 07:52 UTC, doronz88 commented on README.md
> +for your convenience, a link to the gist of all current profiles:
`For`

2022-10-23 08:01 UTC, yotamolenik commented on mobileconfig/mobileconfig.py
> +    def payload_content(self) -> 'PayloadContent':
oops, right

2022-10-23 08:01 UTC, yotamolenik commented on README.md
> +for your convenience, a link to the gist of all current profiles:
done

2022-10-23 08:51 UTC, doronz88 requested changes
another extra line

2022-10-23 08:51 UTC, doronz88 commented on mobileconfig/mobileconfig.py
> +
remove this line

2022-10-23 08:56 UTC, yotamolenik commented on mobileconfig/mobileconfig.py
> +
done

2022-10-23 08:58 UTC, doronz88 requested changes
This code cannot work

2022-10-23 08:58 UTC, doronz88 commented on mobileconfig/mobileconfig.py
> +class LoggingPayload(PayloadContent):ֿ
Remove the character at the end of this line

2022-10-23 09:01 UTC, yotamolenik commented on mobileconfig/mobileconfig.py
> +class LoggingPayload(PayloadContent):ֿ
done

2022-10-23 10:01 UTC, doronz88 requested changes

2022-10-23 10:01 UTC, doronz88 commented on mobileconfig/__main__.py
> +import mdutils
reorder imports

2022-10-23 10:26 UTC, doronz88 approved these changes

2022-10-23 11:27 UTC, merged